[package]
org = "ballerina"
name = "websub_tests"
version = "2.13.0"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
path = "../native/build/libs/websub-native-2.13.0.jar"
