[package]
org = "ballerina"
name = "websub_tests"
version = "2.10.0"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
path = "../native/build/libs/websub-native-2.10.0-SNAPSHOT.jar"
