[package]
org = "ballerina"
name = "websub"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["websub", "subscriber", "service", "listener"]
repository = "https://github.com/ballerina-platform/module-ballerina-websub"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.7.0"

[platform.java11]
graalvmCompatible = true

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "websub-native"
version = "@toml.version@"
path = "../native/build/libs/websub-native-@project.version@.jar"
