[package]
org = "ballerina"
name = "websub"
version = "2.6.1"
authors = ["Ballerina"]
keywords = ["websub", "subscriber", "service", "listener"]
repository = "https://github.com/ballerina-platform/module-ballerina-websub"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.4.0"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "websub-native"
version = "2.6.1"
path = "../native/build/libs/websub-native-2.6.1-SNAPSHOT.jar"
