[package]
org = "ballerina"
name = "websub"
version = "2.9.0"
authors = ["Ballerina"]
keywords = ["websub", "subscriber", "service", "listener"]
repository = "https://github.com/ballerina-platform/module-ballerina-websub"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.7.0"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "websub-native"
version = "2.9.0"
path = "../native/build/libs/websub-native-2.9.0-SNAPSHOT.jar"
