[package]
org = "ballerina"
name = "websub"
version = "2.13.0"
authors = ["Ballerina"]
keywords = ["websub", "subscriber", "service", "listener"]
repository = "https://github.com/ballerina-platform/module-ballerina-websub"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.11.0"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "websub-native"
version = "2.13.0"
path = "../native/build/libs/websub-native-2.13.0.jar"
